version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
    - '3000:3000'
    environment:
      MONGODB_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
