import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import { CustomProviders } from "./provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className=" max-w-8xl mx-auto  bg-transparent h-full min-h-[100vh]">
          <CustomProviders>
            {children}
          </CustomProviders>
        </main>
        <Footer/>
      </body>
    </html>
  );
}

